<?php

namespace ContainerDGhxfj3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A4OPCmNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A4OPCmN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\StatistiqueController::logement' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\StatistiqueController::logement()', 'getStatistiqueControllerlogementService', true],
            'App\\Controller\\StatistiqueController::departement' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\StatistiqueController::departement()', 'getStatistiqueControllerdepartementService', true],
            'App\\Controller\\StatistiqueController::region' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\StatistiqueController::region()', 'getStatistiqueControllerregionService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\StatistiqueController:logement' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\StatistiqueController::logement()', 'getStatistiqueControllerlogementService', true],
            'App\\Controller\\StatistiqueController:departement' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\StatistiqueController::departement()', 'getStatistiqueControllerdepartementService', true],
            'App\\Controller\\StatistiqueController:region' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\StatistiqueController::region()', 'getStatistiqueControllerregionService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\StatistiqueController::logement' => '?',
            'App\\Controller\\StatistiqueController::departement' => '?',
            'App\\Controller\\StatistiqueController::region' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\StatistiqueController:logement' => '?',
            'App\\Controller\\StatistiqueController:departement' => '?',
            'App\\Controller\\StatistiqueController:region' => '?',
        ]);

        if (isset($container->privates['.service_locator.A4OPCmN'])) {
            return $container->privates['.service_locator.A4OPCmN'];
        }

        return $container->privates['.service_locator.A4OPCmN'] = $instance;
    }
}
